### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by Impotpie** [rossnoah/PerPlayerKit#3]
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
disabling plugin.

**Comment by Impotpie** [comment]
full error:
[18:15:36 ERROR]: Error occurred while enabling PerPlayerKit v1.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
        at net.vanillapractice.perplayerkit.PerPlayerKit.onEnable(PerPlayerKit.java:73) ~[PerPlayerKit-1.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:421) ~[PlugManX-2.3.8.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX-2.3.8.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX-2.3.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[18:15:36 INFO]: [PerPlayerKit] Disabling PerPlayerKit v1.1
[18:15:36 ERROR]: Error occurred while disabling PerPlayerKit v1.1
java.lang.NullPointerException: Cannot invoke "net.vanillapractice.perplayerkit.sql.PerPlayerKitDatabase.disconnect()" because "this.database" is null
        at net.vanillapractice.perplayerkit.PerPlayerKit.onDisable(PerPlayerKit.java:181) ~[PerPlayerKit-1.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.load(PaperPluginUtil.java:421) ~[PlugManX-2.3.8.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:116) ~[PlugManX-2.3.8.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX-2.3.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2191) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by rossnoah** [comment]
@Impotpie You are not allowed to use this code. I will refer you to the license.  This project is source available, not open source.
https://github.com/rossnoah/PerPlayerKit/blob/main/LICENSE.txt

**Comment by Impotpie** [comment]
> @Impotpie You are not allowed to use this code. I will refer you to the license. This project is source available, not open source. https://github.com/rossnoah/PerPlayerKit/blob/main/LICENSE.txt


I will rewrited it ;))

**Comment by rossnoah** [comment]
You are not allowed to use to source code in any way. You cant copy from it, you can not use it in any way.
